"""
문제 설명
다음 코드는 3을 0으로 나누고 있습니다. 나눗셈 연산은 0으로 나눌 수 없기 때문에 문제의 코드를 실행하면 에러가 발생합니다. 에러의 이름을 확인하고 try except문으로 코드의 2번째 줄을 감싸서 에러가 발생할 경우 4번째 줄이 출력되도록 만들어 보세요.

프로그래밍을 하다 만나는 다양한 오류들은 유연하게 프로그래밍 할 수 있게 도와주는 도구가 되기도 합니다. try except를 이용하면 에러의 이름을 활용하여 에러를 코드 내에서 처리할 수 있습니다.

아래의 쓰임을 참고하여 문제를 해결해 보세요.

try:
    # 에러가 발생할 가능성이 있는 코드
except Exception: # 에러 종류
    #에러가 발생 했을 경우 처리할 코드

"""

try:
    a = 3/0
except Exception:
    print("0으로 나눌 수 없습니다.")